const GLOBAL_BG = 'SET_GLOBAL_BG';
const GLOBAL_ORIENT_AXIS = 'SET_GLOBAL_ORIENT_AXIS';
const GLOBAL_ORIENT_PRESET = 'SET_GLOBAL_ORIENT_PRESET';
const GLOBAL_AXIS_TYPE = 'SET_GLOBAL_AXIS_TYPE';

const SHOW_APP = 'SHOW_APP';
const SHOW_LANDING = 'SHOW_LANDING';

const VIEWS_SWAP_ORDER = 'VIEWS_SWAP_ORDER';
const VIEWS_REORDER_QUAD = 'VIEWS_REORDER_QUAD';
const SET_VIEWS = 'SET_VIEWS';
const VIEWS_INIT_DATA = 'VIEWS_INIT_DATA';
const VIEW_SET_BACKGROUND = 'VIEW_SET_BACKGROUND';

export default {
  GLOBAL_BG,
  GLOBAL_ORIENT_AXIS,
  GLOBAL_ORIENT_PRESET,
  GLOBAL_AXIS_TYPE,
  SHOW_APP,
  SHOW_LANDING,
  VIEWS_SWAP_ORDER,
  VIEWS_REORDER_QUAD,
  SET_VIEWS,
  VIEWS_INIT_DATA,
  VIEW_SET_BACKGROUND,
};
