const GLOBAL_BG = 'SET_GLOBAL_BG';
const GLOBAL_ORIENT_AXIS = 'SET_GLOBAL_ORIENT_AXIS';
const GLOBAL_ORIENT_PRESET = 'SET_GLOBAL_ORIENT_PRESET';
const GLOBAL_AXIS_TYPE = 'SET_GLOBAL_AXIS_TYPE';

const SHOW_APP = 'SHOW_APP';
const SHOW_LANDING = 'SHOW_LANDING';

export default {
  GLOBAL_BG,
  GLOBAL_ORIENT_AXIS,
  GLOBAL_ORIENT_PRESET,
  GLOBAL_AXIS_TYPE,
  SHOW_APP,
  SHOW_LANDING,
};
