export const GLOBAL_BG = 'SET_GLOBAL_BG';
export const GLOBAL_ORIENT_AXIS = 'SET_GLOBAL_ORIENT_AXIS';
export const GLOBAL_ORIENT_PRESET = 'SET_GLOBAL_ORIENT_PRESET';
export const GLOBAL_AXIS_TYPE = 'SET_GLOBAL_AXIS_TYPE';

export default {
  GLOBAL_BG,
  GLOBAL_ORIENT_AXIS,
  GLOBAL_ORIENT_PRESET,
  GLOBAL_AXIS_TYPE,
};
